/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'btu' at '9/24/16 2:23 PM' with Gradle 2.5
 *
 * @author btu, @date 9/24/16 2:23 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
